### ISSUE TITLE
Implementing symlink support raises 2 issues/bugs

### ISSUE THREAD

**Issue by jmaddencom** [lwoggardner/ffi-libfuse#21]
FFI::Stat is missing a `file` or `dir` equivalent for symlinks. I worked around this with: 

```
module FFI
  class Stat
    def link(mode:, size:, uid: Process.uid, gid: Process.gid, **args)
      mode = ((S_IFLNK & S_IFMT) | (mode & 0o777))
      fill(mode: mode, size: size, uid: uid, gid: gid, **args)
    end
  end
end
```

The next step is implementing a readlink() but this runs into an issue in the Ruby Adapter where put_string is only sending one arg. This fixes it: 

```
module FFI
  module Libfuse
    module Adapter
      module Ruby
        class << self
          def readlink(buf, size)
            link = yield
            raise Errno::ENOTSUP unless link
            raise Errno::ENAMETOOLONG unless link.size < size # includes terminating NUL

            buf.put_string(0, link)
            0
          end
        end
      end
    end
  end
end
```
I can open a PR on these now or wait until I've covered the rest of what I dig up, let me know how best to proceed.

**Comment by lwoggardner** [comment]
Thanks. Re PR now or later, Up to you. It will take me a few days to get to look into it further.

**Comment by lwoggardner** [comment]
Notes while looking at this...
* Probably should also implement FFI::Stat#link? 
* basic_test has non implemented specs for links - (to resolve any libfuse side understanding)
* ruby adapter is only tested through samples
* possibly could add symlink support to VirtualDir and test via MemoryFS sample
